### ISSUE TITLE
test that services persist data across restarts (e.g. http sessions)

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/enochecker_test#23]

**Comment by Trolldemorted** [comment]
... and test whether the service can be restarted *at all* 😇

**Comment by ldruschk** [comment]
With the current structure of enochecker_test, that would not be possible since we are only using the HTTP-API of the checker and are not able to restart the service

**Comment by Trolldemorted** [comment]
Where should I track issues for the CI flows? I thought this repository might be the best fit
