### ISSUE TITLE
Fix pytest assert rewriting

### ISSUE THREAD

**Issue by ldruschk** [enowars/enochecker_test#4]
https://docs.pytest.org/en/stable/reference.html#pytest-register-assert-rewrite

by default pytest only rewrites asserts for tests discovered through the built-in test discovery mechanisms

**Comment by Trolldemorted** [comment]
Are there pytest-asserts which we could use without rewriting magic?

**Comment by ldruschk** [comment]
> Are there pytest-asserts which we could use without rewriting magic?

I don't think so
